name: Nuget Pkg Build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Build
      run: dotnet build LineWalker -c Release
    #- name: Test
    #  run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack LineWalker -c Release --no-build --output . --include-symbols --include-source -p:SymbolPackageFormat=snupkg
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGETAPIKEY}} --source https://api.nuget.org/v3/index.json
